scratchpads:
  - name: "spotify"
    app: "Spotify"
    open-command: "open /Applications/Spotify.app"
  - name: "calendar"
    app: "Calendar"
    open-command: "open /System/Applications/Calendar.app"
  - name: "scratchpad"
    title: "^SCRATCHPAD$"
    app: "Alacritty"
    open-command: "/Applications/Alacritty.app/Contents/MacOS/alacritty -t SCRATCHPAD --option window.dimensions.columns=90 --option window.dimensions.lines=40 -e bash -c ~/.local/bin/scratch"
  - name: "notes"
    title: "^VIMNOTES$"
    app: "Alacritty"
    open-command: "/Applications/Alacritty.app/Contents/MacOS/alacritty -t VIMNOTES --option window.dimensions.columns=110 --option window.dimensions.lines=40 -e /bin/bash -c ~/.local/bin/wiki"
  - name: "apple-notes"
    title: "^Notes$"
    app: "Notes"
    open-command: "open /System/Applications/Notes.app"
  - name: "terminal"
    title: "^SCRATCHTERM$"
    app: "Alacritty"
    open-command: "/Applications/Alacritty.app/Contents/MacOS/alacritty -t SCRATCHTERM --option window.dimensions.columns=90 --option window.dimensions.lines=40"
  - name: "rocket-chat"
    app: "Rocket.Chat"
    open-command: "open /Applications/Rocket.Chat.app"
  - name: "discord"
    app: "Discord"
    open-command: "open /Applications/Discord.app"
  - name: "messages"
    app: "Messages"
    open-command: "open /System/Applications/Messages.app"
# scratchpad-workspace: 9
